version: '3.8'

services:
  jenkins-blueocean:
    image: myjenkins-blueocean:2.452.3-1
    container_name: jenkins-blueocean
    restart: on-failure
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro
    ports:
      - "8080:8080"
      - "50000:50000"
    networks:
      - jenkins

volumes:
  jenkins-data:
  jenkins-docker-certs:

networks:
  jenkins:
